jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: yml
      data-id: jeecg-gateway-router
spring:
  redis:
    database: 0
    host: jeecg-boot-redis
    port: 6379
    password:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        health-check-critical-timeout: 30s
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
        instance-id: ${spring.application.name}-${server.port}
knife4j:
  production: false
