jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: yml
      data-id: jeecg-gateway-router
spring:
  redis:
    database: 1
    host: 162.14.66.67
    password: fxtd@2025
    port: 6389
knife4j:
  production: false
