jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: yml
      data-id: jeecg-gateway-router
spring:
  redis:
    database: 1
    host: 127.0.0.1
    password:
    port: 6379
knife4j:
  production: false
