jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: yml
      data-id: jeecg-gateway-router
spring:
  application:
    name: xinwei5-gateway
  cloud:
    nacos:
      discovery:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            #springboot2.4后需用allowedOriginPatterns
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        [ {
          "id": "xinwei5-auth",
          "order": 0,
          "predicates": [ {
            "name": "Path",
            "args": {
              "_genkey_0": "/sys/**",
              "_genkey_1": "/jmreport/**",
              "_genkey_3": "/online/**",
              "_genkey_4": "/generic/**",
              "_genkey_5": "/oauth2/**",
              "_genkey_6": "/drag/**",
              "_genkey_7": "/actuator/**",
              "_genkey_8": "/airag/**",
              "_genkey_9": "/openapi/**",
              "_genkey_10": "/websocket/**"
            }
          } ],
          "filters": [ ],
          "uri": "lb://xinwei5-auth"
        }, {
          "id": "xinwei5-generate",
          "order": 1,
          "predicates": [ {
            "name": "Path",
            "args": {
              "_genkey_0": "/generate/**"
            }
          } ],
          "filters": [ ],
          "uri": "lb://xinwei5-generate"
        },{
          "id": "xinwei5-ftu",
          "order": 2,
          "predicates": [ {
            "name": "Path",
            "args": {
              "_genkey_0": "/ftu/**"
            }
          } ],
          "filters": [ ],
          "uri": "lb://xinwei5-ftu"
        } ]
  redis:
    database: 1
    host: 162.14.66.67
    password: fxtd@2025
    port: 6389
knife4j:
  production: false
server:
  port: 9856
